### ISSUE TITLE
error while installing

### ISSUE THREAD

**Issue by jayendramadaram** [jtgrassie/pyrx#12]
pip install git+https://github.com/jtgrassie/pyrx
Collecting git+https://github.com/jtgrassie/pyrx
  Cloning https://github.com/jtgrassie/pyrx to c:\users\*****\appdata\local\temp\pip-req-build-j3ekkbso
  Running command git clone --filter=blob:none --quiet https://github.com/jtgrassie/pyrx 'C:\Users\****\AppData\Local\Temp\pip-req-build-j3ekkbso'
  Resolved https://github.com/jtgrassie/pyrx to commit 032f96b087cd09c24eb3ae18dc7dc593a3d7977d
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyrx
  Building wheel for pyrx (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "C:\Users\****\AppData\Local\Temp\pip-req-build-j3ekkbso\setup.py", line 21, in run
          out = subprocess.check_output(['cmake', '--version'])
        File "c:\users\***\appdata\local\programs\python\python39\lib\subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "c:\users\****\appdata\local\programs\python\python39\lib\subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "c:\users\***\appdata\local\programs\python\python39\lib\subprocess.py", line 947, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "c:\users\***\appdata\local\programs\python\python39\lib\subprocess.py", line 1416, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\***\AppData\Local\Temp\pip-req-build-j3ekkbso\setup.py", line 59, in <module>
          setup(
        File "c:\users\*******\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "c:\users\***********\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "c:\users\************\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "c:\users\*****\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\jayendra\AppData\Local\Temp\pip-req-build-j3ekkbso\setup.py", line 23, in run
          raise RuntimeError("CMake must be installed to build the following extensions: " +
      RuntimeError: CMake must be installed to build the following extensions: pyrx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyrx
  Running setup.py clean for pyrx
Failed to build pyrx
Installing collected packages: pyrx
  Running setup.py install for pyrx ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pyrx did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running install
      running build
      running build_ext
      Traceback (most recent call last):
        File "C:\Users\jayendra\AppData\Local\Temp\pip-req-build-j3ekkbso\setup.py", line 21, in run
          out = subprocess.check_output(['cmake', '--version'])
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\subprocess.py", line 947, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\subprocess.py", line 1416, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\jayendra\AppData\Local\Temp\pip-req-build-j3ekkbso\setup.py", line 59, in <module>
          setup(
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py", line 61, in run
          return orig.install.run(self)
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\command\install.py", line 546, in run
          self.run_command('build')
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "c:\users\jayendra\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\************\AppData\Local\Temp\pip-req-build-j3ekkbso\setup.py", line 23, in run
          raise RuntimeError("CMake must be installed to build the following extensions: " +
      RuntimeError: CMake must be installed to build the following extensions: pyrx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyrx

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the 'c:\users\*******\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.
PS C:\tai_jutsu\crypto_mining\monero-powpy> pip install git+https://github.com/jtgrassie/pyrx

**Comment by ghost** [comment]
Try pip3 instead of pip in the command.

**Comment by jtgrassie** [comment]
It's literally _telling_ you what you need:

> RuntimeError: **CMake must be installed** to build the following extensions: pyrx
